import { Product, Order, Customer, ContentSection } from './types';

export const CATEGORIES = [
  { id: 'all', name: 'Todos' },
  { id: 'black-friday', name: 'Black Friday', isHighlight: true },
  { id: 'disposables', name: 'Pods Descartáveis' },
  { id: 'juices-br', name: 'Juices Nacionais' },
  { id: 'juices-import', name: 'Juices Importados' },
  { id: 'salts-br', name: 'SaltNic Nacional' },
  { id: 'salts-import', name: 'SaltNic Importado' },
  { id: 'pods', name: 'Pod Systems' },
  { id: 'coils', name: 'Coils & Acessórios' },
];

export const HERO_BANNERS = [
  {
    id: 1,
    title: "BLACK FRIDAY VAPE",
    subtitle: "Descontos de até 60% em toda a linha premium de Pods e Juices.",
    image: "https://placehold.co/1920x600/1a1a1a/FFF?text=BLACK+FRIDAY+VAPE+PROMO&font=roboto",
    cta: "Aproveitar Agora",
    color: "from-purple-900 to-indigo-900"
  },
  {
    id: 2,
    title: "XROS SERIES: A EVOLUÇÃO DO SABOR",
    subtitle: "DISPOSITIVOS PREMIUM. SESSÕES INIGUALÁVEIS.",
    image: "https://placehold.co/1920x600/0a0a0a/FFF?text=XROS+SERIES&font=roboto",
    cta: "Compre Agora",
    color: "from-blue-900 via-purple-900 to-orange-900"
  },
  {
    id: 3,
    title: "NOVO IGNITE V80",
    subtitle: "A revolução do sabor chegou. 8000 puffs de pura tecnologia.",
    image: "https://placehold.co/1920x600/064e3b/FFF?text=NEW+IGNITE+V80+LAUNCH&font=roboto",
    cta: "Conhecer Lançamento",
    color: "from-blue-900 to-indigo-900"
  },
  {
    id: 4,
    title: "JUICES IMPORTADOS",
    subtitle: "As melhores marcas do mundo com preços do Brasil.",
    image: "https://placehold.co/1920x600/1e3a8a/FFF?text=PREMIUM+IMPORTED+JUICES&font=roboto",
    cta: "Ver Coleção",
    color: "from-blue-900 to-slate-900"
  }
];

export const BRANDS = [
  { name: "Ignite", logo: "https://placehold.co/150x60/222/FFF?text=IGNITE" },
  { name: "Elfbar", logo: "https://placehold.co/150x60/222/FFF?text=ELFBAR" },
  { name: "Vaporesso", logo: "https://placehold.co/150x60/222/FFF?text=VAPORESSO" },
  { name: "Nasty", logo: "https://placehold.co/150x60/222/FFF?text=NASTY" },
  { name: "Voopoo", logo: "https://placehold.co/150x60/222/FFF?text=VOOPOO" },
  { name: "Smok", logo: "https://placehold.co/150x60/222/FFF?text=SMOK" },
  { name: "Geekvape", logo: "https://placehold.co/150x60/222/FFF?text=GEEKVAPE" },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Pod System X-Pro 2',
    description: 'O mais avançado sistema de pod do mercado. Bateria de longa duração.',
    price: 249.90,
    originalPrice: 299.90,
    category: 'pods',
    images: ['/images/product-1.svg'],
    rating: 4.8,
    reviewsCount: 124,
    stock: 15,
    isBestSeller: true,
    flavors: ['Preto Carbono', 'Prata'],
  },
  {
    id: '2',
    name: 'Juice NicSalt Mint Freeze',
    description: 'Refrescância pura. Menta gelada ideal para o verão.',
    price: 89.90,
    category: 'salts-br',
    images: ['/images/product-2.svg'],
    rating: 4.5,
    reviewsCount: 56,
    stock: 40,
    isNew: true,
    nicotine: ['35mg', '50mg'],
  },
  {
    id: '3',
    name: 'Ignite V50 Descartável',
    description: '5000 puffs de puro sabor. Design ergonômico.',
    price: 110.00,
    originalPrice: 130.00,
    category: 'disposables',
    images: ['/images/product-3.svg'],
    rating: 4.9,
    reviewsCount: 342,
    stock: 5,
    isBestSeller: true,
    flavors: ['Watermelon', 'Grape'],
  },
  {
    id: '4',
    name: 'Coil Mesh Reposição',
    description: 'Resistências de malha alta durabilidade para Vaporesso.',
    price: 75.00,
    category: 'coils',
    images: ['/images/product-4.svg'],
    rating: 4.7,
    reviewsCount: 89,
    stock: 100,
  },
  {
    id: '5',
    name: 'Juice Gold Label Tobacco',
    description: 'Tabaco clássico com notas sutis de caramelo.',
    price: 149.90,
    category: 'juices-import',
    images: ['/images/product-5.svg'],
    rating: 5.0,
    reviewsCount: 12,
    stock: 8,
    nicotine: ['3mg', '6mg'],
  },
  {
    id: '6',
    name: 'Pod System Mini Fit',
    description: 'Compacto, discreto e potente. Cabe no bolso.',
    price: 129.90,
    originalPrice: 159.90,
    category: 'pods',
    images: ['/images/product-6.svg'],
    rating: 4.2,
    reviewsCount: 45,
    stock: 22,
  },
  {
    id: '7',
    name: 'Elfbar BC10000',
    description: 'A nova era dos descartáveis com display digital.',
    price: 115.00,
    category: 'disposables',
    images: ['/images/product-7.svg'],
    rating: 4.9,
    reviewsCount: 18,
    stock: 150,
    isNew: true,
  },
  {
    id: '8',
    name: 'Nasty Juice Cush Man',
    description: 'A melhor manga do mundo. Doce e refrescante.',
    price: 95.00,
    originalPrice: 110.00,
    category: 'juices-import',
    images: ['/images/product-8.svg'],
    rating: 4.8,
    reviewsCount: 220,
    stock: 30,
    isBestSeller: true,
  }
];

// Mock Orders
export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-001',
    date: new Date(2024, 0, 15).toISOString(),
    status: 'pending',
    total: 359.80,
    items: [
      { ...MOCK_PRODUCTS[0], quantity: 1, selectedFlavor: 'Preto Carbono' },
      { ...MOCK_PRODUCTS[2], quantity: 1, selectedFlavor: 'Watermelon' },
    ],
    customerId: 'CUST-001',
    customerName: 'João Silva',
    customerEmail: 'joao.silva@email.com',
    shippingAddress: 'Rua das Flores, 123 - São Paulo, SP',
  },
  {
    id: 'ORD-002',
    date: new Date(2024, 0, 14).toISOString(),
    status: 'paid',
    total: 89.90,
    items: [
      { ...MOCK_PRODUCTS[1], quantity: 1, selectedNicotine: '35mg' },
    ],
    customerId: 'CUST-002',
    customerName: 'Maria Santos',
    customerEmail: 'maria.santos@email.com',
    shippingAddress: 'Av. Paulista, 1000 - São Paulo, SP',
  },
  {
    id: 'ORD-003',
    date: new Date(2024, 0, 13).toISOString(),
    status: 'shipped',
    total: 220.00,
    items: [
      { ...MOCK_PRODUCTS[2], quantity: 2, selectedFlavor: 'Grape' },
    ],
    customerId: 'CUST-003',
    customerName: 'Pedro Oliveira',
    customerEmail: 'pedro.oliveira@email.com',
    shippingAddress: 'Rua Augusta, 500 - São Paulo, SP',
  },
  {
    id: 'ORD-004',
    date: new Date(2024, 0, 12).toISOString(),
    status: 'delivered',
    total: 149.90,
    items: [
      { ...MOCK_PRODUCTS[4], quantity: 1, selectedNicotine: '6mg' },
    ],
    customerId: 'CUST-004',
    customerName: 'Ana Costa',
    customerEmail: 'ana.costa@email.com',
    shippingAddress: 'Rua Consolação, 200 - São Paulo, SP',
  },
  {
    id: 'ORD-005',
    date: new Date(2024, 0, 11).toISOString(),
    status: 'paid',
    total: 404.80,
    items: [
      { ...MOCK_PRODUCTS[0], quantity: 1, selectedFlavor: 'Prata' },
      { ...MOCK_PRODUCTS[5], quantity: 1 },
      { ...MOCK_PRODUCTS[7], quantity: 1 },
    ],
    customerId: 'CUST-001',
    customerName: 'João Silva',
    customerEmail: 'joao.silva@email.com',
    shippingAddress: 'Rua das Flores, 123 - São Paulo, SP',
  },
];

// Mock Customers
export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'CUST-001',
    name: 'João Silva',
    email: 'joao.silva@email.com',
    phone: '(11) 98765-4321',
    address: 'Rua das Flores, 123',
    city: 'São Paulo',
    state: 'SP',
    totalOrders: 2,
    totalSpent: 764.70,
    lastOrderDate: new Date(2024, 0, 15).toISOString(),
    registrationDate: new Date(2023, 11, 1).toISOString(),
  },
  {
    id: 'CUST-002',
    name: 'Maria Santos',
    email: 'maria.santos@email.com',
    phone: '(11) 97654-3210',
    address: 'Av. Paulista, 1000',
    city: 'São Paulo',
    state: 'SP',
    totalOrders: 1,
    totalSpent: 89.90,
    lastOrderDate: new Date(2024, 0, 14).toISOString(),
    registrationDate: new Date(2023, 11, 15).toISOString(),
  },
  {
    id: 'CUST-003',
    name: 'Pedro Oliveira',
    email: 'pedro.oliveira@email.com',
    phone: '(11) 96543-2109',
    address: 'Rua Augusta, 500',
    city: 'São Paulo',
    state: 'SP',
    totalOrders: 1,
    totalSpent: 220.00,
    lastOrderDate: new Date(2024, 0, 13).toISOString(),
    registrationDate: new Date(2023, 10, 20).toISOString(),
  },
  {
    id: 'CUST-004',
    name: 'Ana Costa',
    email: 'ana.costa@email.com',
    phone: '(11) 95432-1098',
    address: 'Rua Consolação, 200',
    city: 'São Paulo',
    state: 'SP',
    totalOrders: 1,
    totalSpent: 149.90,
    lastOrderDate: new Date(2024, 0, 12).toISOString(),
    registrationDate: new Date(2023, 9, 5).toISOString(),
  },
  {
    id: 'CUST-005',
    name: 'Carlos Ferreira',
    email: 'carlos.ferreira@email.com',
    phone: '(11) 94321-0987',
    address: 'Rua Oscar Freire, 300',
    city: 'São Paulo',
    state: 'SP',
    totalOrders: 0,
    totalSpent: 0,
    lastOrderDate: new Date(2023, 11, 1).toISOString(),
    registrationDate: new Date(2024, 0, 10).toISOString(),
  },
];

// Mock Content Sections
export const MOCK_CONTENT_SECTIONS: ContentSection[] = [
  {
    id: 'CONT-001',
    type: 'banner',
    title: 'BLACK FRIDAY VAPE',
    content: 'Descontos de até 60% em toda a linha premium de Pods e Juices.',
    imageUrl: 'https://placehold.co/1920x600/1a1a1a/FFF?text=BLACK+FRIDAY+VAPE+PROMO',
    order: 1,
    isActive: true,
    cta: 'Aproveitar Agora',
    link: 'catalog',
  },
  {
    id: 'CONT-002',
    type: 'text',
    title: 'Sobre Nós',
    content: 'A White Cloud Brasil é referência em produtos de vaporização premium. Oferecemos qualidade, variedade e os melhores preços do mercado.',
    order: 2,
    isActive: true,
  },
  {
    id: 'CONT-003',
    type: 'category',
    title: 'Categoria Destaque - Pods Descartáveis',
    content: 'disposables',
    order: 3,
    isActive: true,
  },
  {
    id: 'CONT-004',
    type: 'image',
    title: 'Imagem Promocional - Novo Lançamento',
    content: 'Conheça o novo Ignite V80',
    imageUrl: 'https://placehold.co/800x400/064e3b/FFF?text=NEW+IGNITE+V80',
    order: 4,
    isActive: true,
  },
  {
    id: 'CONT-005',
    type: 'banner',
    title: 'XROS SERIES: A EVOLUÇÃO DO SABOR',
    content: 'DISPOSITIVOS PREMIUM. SESSÕES INIGUALÁVEIS.',
    imageUrl: 'https://placehold.co/1920x600/0a0a0a/FFF?text=XROS+SERIES',
    order: 2,
    isActive: true,
    cta: 'Compre Agora',
    link: 'catalog',
  },
  {
    id: 'CONT-006',
    type: 'banner',
    title: 'NOVO IGNITE V80',
    content: 'A revolução do sabor chegou. 8000 puffs de pura tecnologia.',
    imageUrl: 'https://placehold.co/1920x600/064e3b/FFF?text=NEW+IGNITE+V80+LAUNCH',
    order: 3,
    isActive: true,
    cta: 'Conhecer Lançamento',
    link: 'catalog',
  },
  {
    id: 'CONT-007',
    type: 'banner',
    title: 'Banner Secundário - Juices Importados',
    content: 'As melhores marcas do mundo com preços do Brasil.',
    imageUrl: 'https://placehold.co/1920x600/1e3a8a/FFF?text=PREMIUM+IMPORTED+JUICES',
    order: 5,
    isActive: false,
    cta: 'Ver Coleção',
    link: 'catalog',
  },
];